config/routes.rb
Rails.application.routes.draw do

  get 'account/edit_profile'
  post 'account/edit_profile'

  get 'password/forgot_password'
  post 'password/forgot_password'

  get 'password/reset_password'
  post 'password/reset_password'

  get 'account/signup'
  post 'account/signup'

  get 'account/login'
  post 'account/login'

  get 'account/dashboard'
  get 'account/logout'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    has_one_attached :header_image
    attr_accessor :password

    validates :first_name, presence: true
    validates :mobile, length: { is: 10 }
    validates :email, uniqueness: true, length: {in: 5..50}
    validates :password, presence: true, confirmation: true, length: {in: 5..17}, on: :create

    before_save :encrypt_new_password

    def self.authenticate(email, password)
        user = find_by_email(email)
        if user && user.authenticated_password(password)
            return user
        end
    end
    
    def authenticated_password(password)
        self.encrypted_password == encrypt(password)
    end

    def self.create_random_password
        (0...8).map { (65 + rand(26)).chr }.join
    end

    protected


    def encrypt_new_password
        return if password.blank?
        self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
        Digest::SHA1.hexdigest(string)
    end


end

app/controllers/account_controller.rb
class AccountController < ApplicationController
  def signup
    @user = User.new
    if request.post?
      @user = User.new(user_params)
      if @user.save
        UserNotifierMailer.signup_alert(@user).deliver
        redirect_to "/account/login", notice: 'Successfully created account'
      else
        render :signup
      end
    end
  end

  def login
    if request.post?
      @user = User.authenticate(params[:email], params[:password])
      if @user
        session[:user] = @user.id
        redirect_to :action=>:dashboard
      else
        flash[:notice] = "Invalid email/password"
        render :action=>:login  
      end
    end
  end

  def logout
    flash[:notice] = "You are logged out"
    session.clear
    redirect_to account_login_url
  end

  def edit_profile
    @user = User.find(session[:user])
    if request.post?
      if @user
        @user.update(:first_name=>params[:first_name], :last_name=>params[:last_name], :mobile=>params[:mobile], :header_image=>params[:header_image])
        redirect_to account_dashboard_url
      else
        flash[:notice] = "Please enter the valid details!"
        render :action=>edit_profile
      end
    end
  end

  def dashboard
    @user = User.find(session[:user])
  end

  private
  def user_params
    params.permit(:first_name,:last_name,:email,:password,:password_confirmation,:encrypted_password,:mobile,:date_of_birth)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/password_controller.rb
class PasswordController < ApplicationController
  def forgot_password
    if request.post?
      @user = User.find_by_email(params[:email])
      if @user
        new_password = User.create_random_password
        UserNotifierMailer.forgot_password_alert(@user, new_password).deliver
        @user.update(:password=>new_password)
        redirect_to account_login_url
      else
        flash[:notice] = "Invalid email id. Please enter valid email address"
        render :action=>forgot_password 
      end
    end
  end

  def reset_password
    @user = User.find_by_id(session[:user])
    if request.post?
      if @user
        new_password = params[:password]
        @user.update(:password=>new_password)
        UserNotifierMailer.reset_password_alert(@user, new_password).deliver
        redirect_to account_login_url
      else
        flash[:notice] = "Please login to reset password"
        render :action=>reset_password 
      end
    end
  end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/password_helper.rb
module PasswordHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="links">
 <% if session[:user] %>
   <%= link_to "Edit Profile", account_edit_profile_path, {:style=>'color:#FFFFFF;', :class => "css_class"} %> |
   <%= link_to "Reset Password", password_reset_password_path,{:style=>'color:#FFFFFF;', :class => "css_class"} %>|
   <%= link_to "Logout", account_logout_path, {:style=>'color:#FFFFFF;', :class => "css_class"} %>
   <% else %>
   <%= link_to "Sign Up", account_signup_path, {:style=>'color:#FFFFFF;', :class => "css_class"} %>
   <%= link_to "Login", account_login_path, {:style=>'color:#FFFFFF;', :class => "css_class"} %>
 <% end %>
</div>
 <div class="container">
    <input type="checkbox" id="flip">
    <div class="cover">
      <div class="front">
        <img src="/assets/frontImg.jpg" alt="">
        <div class="text">
          <span class="text-1">Every new friend is a <br> new adventure</span>
          <span class="text-2">Let's get connected</span>
        </div>
      </div>
      <div class="back">
        <img class="backImg" src="/assets/backImg.jpg" alt="">
        <div class="text">
          <span class="text-1">Complete miles of journey <br> with one step</span>
          <span class="text-2">Let's get started</span>
        </div>
      </div>
    </div>
    <div class="forms">
        <div class="form-content">
          <%= yield %>
       
      </div>
       
    </div>
  </body>
</html>

app/views/password/forgot_password.html.erb
<div class="signup-form">
  <div class="title">Forgot Password</div>
  <%= form_with url: "/password/forgot_password", method: :post do |f| %>
    <div class="input-boxes">    
      <div class="input-box" >
        <%= f.text_field :email, placeholder: "Enter email" %>
      </div>
    </div>
    <div class="button input-box">         
      <div class="button input-box" >
        <%= f.submit  "Submit" %> 
      </div>
    </div>
  <% end %>  
</div>

app/views/password/reset_password.html.erb
<%= form_with url: "/password/reset_password", method: :post do |form|%>
  <%= flash[:notice] %>
  <div class="title">Reset password</div> 
  <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user to signup:</h2>
        <ul>
          <% @user.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
  <% end %>
  <div class="field">
    <i class="fas fa-lock"></i>
    <%= form.label :password%>
    <%= form.password_field :password %>
  </div>
  <div class="field">
    <i class="fas fa-lock"></i>
    <%= form.label :confirmation_password%>
    <%= form.password_field :password_confirmation %>
  </div>
    <div>
      <%= form.submit "Reset Password" %>
    </div>
  <%= link_to "Login", account_login_path %>
<% end %>